import FluentPostgresDriver

/**
    #### 实现该协议以创建数据库表数据模型

    一个 PGModel 类型对应着数据库中的一个表，你需要集成该协议，并完成一系列设置以创建你的表结构模型

    -----
    ### 创建表数据模型
    以下列出了一个完整的 `users` 数据表的数据模型
    ``` swift
    // 实现协议 PGModel
    final class User: PGModel, @unchecked Sendable {

        // 设置表的名称，请注意不要与其他类型的表冲突
        static let name = "users"

        // 定义该表的所有字段信息，详见 PGFields 协议
        struct Fields: PGFields {
            // 该字段将作为该表的主键，建议每个表都创建至少一个主键
            let id = PGField("id", .uuid).primary
            let email = PGField("email", .string).cons([.sql(.default("null@null.com")), .required])
            let age = PGField("age", .int, true).def(30)
            let createdAt = PGField("create_at", .string, true)
            let updateAt = PGField("update_at", .string).def("2001-02-27")
        }
        
        // 以下关于键值绑定的 @ID, @Field, @Timestamp 等等属性包装器，可参见 [Vapor 官方文档](https://docs.vapor.codes/fluent/model/)

        // 将数据库表 users 中的 id 字段绑定到该模型的 id 属性
        @ID(key: .id)                                                   var id: UUID?
        // 将数据库表 users 中的 email 字段绑定到该模型的 email 属性
        @Field(fields.email)                                            var email: String?
        // 将数据库表 users 中的 age 字段绑定到该模型的 age 属性
        @Field(fields.age)                                              var age: Int?
        // 将数据库表 users 中的 create_at 字段绑定到该模型的 createAt 属性
        @Timestamp(fields.createdAt, on: .create)                       var createdAt: Date?
        // 将数据库表 users 中的 update_at 字段绑定到该模型的 updateAt 属性
        @Timestamp(fields.updateAt, on: .update)                        var updatedAt: Date?
        
        // 数据库表结构生成和迁移，负责与数据库交互，进行表创建，迁移，恢复等等交涉
        // 你需要确保 typealias DataModel = User 中，DataModel 正确地指向你的表数据模块
        // 在此例中指向为 User
        struct MIG: PGMigration, Sendable { typealias DataModel = User }
    }

    // 以上便完全实现了 PGModel 协议
    // 若你愿意，你可以添加一些其他的功能
    extension User {
        convenience init(id: UUID, email: String? = nil, age: Int? = nil) {
            self.init()
            self.id = id
            if email != nil { self.email = email }
            if age != nil { self.age = age }
        }
    }
    ```
    以上创建的表结构等效于使用下面 SQL 语句创建: 
    ``` SQL
    CREATE TABLE IF NOT EXISTS public.users (
        id uuid GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        email text GENERATED BY DEFAULT AS IDENTITY DEFAULT 'null@null.com'::text NOT NULL,
        age bigint GENERATED BY DEFAULT AS IDENTITY DEFAULT 30,
        create_at text GENERATED BY DEFAULT AS IDENTITY,
        update_at text GENERATED BY DEFAULT AS IDENTITY DEFAULT '2001-02-27'::text,
        PRIMARY KEY(id)
    );
    ```
*/
public protocol PGModel: Model, Sendable where Self.MIG.DataModel == Self {
    associatedtype MIG: PGMigration
    associatedtype Fields: PGFields
    /// 表的名称
    static var name: String { get }
    /// 表字段列表的实例
    static var fields: Fields { get }
}

public extension PGModel {
    static var schema: String { Self.name }
    static var fields: Fields { Self.Fields() }
}
