name: test
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request: { types: [opened, reopened, synchronize, ready_for_review] }
  push: { branches: [ develop ] }

jobs:
  unit-tests:
    uses: ./.github/workflows/run-unit-tests.yml
    with:
      with_release_mode_testing: true
      with_tsan: false
      with_musl: true
      extra_musl_flags: --target PgSQL
      ios_xcodebuild_action: ''
      ios_scheme_name: whooshing.toolbox-pgsql
    secrets: inherit

  test-parallel:
    if: ${{ !(github.event.pull_request.draft || false) }}
    runs-on: ubuntu-latest
    container: swift:6.0
    services:
      postgres:
        image: postgres:17.2
        env:
          POSTGRES_DB: testing
          POSTGRES_USER: testing
          POSTGRES_PASSWORD: testing
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out Vapor
        uses: actions/checkout@v4
      - name: Run tests
        run: swift build
